spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver

  jpa:
    generate-ddl: true
#    show-sql: true
    hibernate:
      ddl-auto: update


  freemarker:
    expose-request-attributes: true


upload:
  path: D:/edu/practice/uploads

